// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package repo

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (content,thread_id)
VALUES ($1, $2)
RETURNING id, content, created_at, thread_id
`

type CreateMessageParams struct {
	Content  string `json:"content"`
	ThreadID int32  `json:"thread_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Content, arg.ThreadID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.ThreadID,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one







INSERT INTO thread (title)
VALUES ($1)
RETURNING id, title, created_at
`

// -- name: CreateMessage :one
// INSERT INTO message (thread, sender, content)
// VALUES ($1, $2, $3)
// RETURNING *;
// -- name: GetMessageByID :one
// SELECT * FROM message
// WHERE id = $1;
// -- name: GetMessagesByThread :many
// SELECT * FROM message
// WHERE thread = $1
// ORDER BY created_at DESC;
// -- name: DeleteMessage :exec
// DELETE FROM message WHERE id = $1;
// -- name: UpdateMessage :exec
// UPDATE message
// SET content = $2
// WHERE id = $1
// RETURNING *;
// -- name: CreateThread :one
// INSERT INTO thread (title)
// VALUES ($1)
// RETURNING *;
// -- name: DeleteAll :exec
// DELETE FROM message;
func (q *Queries) CreateThread(ctx context.Context, title string) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, title)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteMessageById = `-- name: DeleteMessageById :exec
DELETE FROM message WHERE id = $1
`

func (q *Queries) DeleteMessageById(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMessageById, id)
	return err
}

const deleteMessageByThreadId = `-- name: DeleteMessageByThreadId :exec
DELETE FROM message WHERE thread_id = $1
`

func (q *Queries) DeleteMessageByThreadId(ctx context.Context, threadID int32) error {
	_, err := q.db.Exec(ctx, deleteMessageByThreadId, threadID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, content, created_at, thread_id FROM message
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.ThreadID,
	)
	return i, err
}

const getMessagesByThread = `-- name: GetMessagesByThread :many
SELECT id, content, created_at, thread_id FROM message
WHERE thread_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMessagesByThread(ctx context.Context, threadID int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE message 
SET content = $2
WHERE id = $1
RETURNING id, content, created_at, thread_id
`

type UpdateMessageParams struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.ID, arg.Content)
	return err
}
