// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (content,thread_id)
VALUES ($1, $2)
RETURNING id, content, created_at, thread_id
`

type CreateMessageParams struct {
	Content  string `json:"content"`
	ThreadID int32  `json:"thread_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Content, arg.ThreadID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.ThreadID,
	)
	return i, err
}

const createProductCategory = `-- name: CreateProductCategory :one
INSERT INTO product_categories (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateProductCategoryParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, createProductCategory, arg.Name, arg.Slug)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductGallery = `-- name: CreateProductGallery :exec
INSERT INTO product_gallery (
    product_id,
    image_url
)
VALUES ($1, $2)
`

type CreateProductGalleryParams struct {
	ProductID *int32 `json:"product_id"`
	ImageUrl  string `json:"image_url"`
}

func (q *Queries) CreateProductGallery(ctx context.Context, arg CreateProductGalleryParams) error {
	_, err := q.db.Exec(ctx, createProductGallery, arg.ProductID, arg.ImageUrl)
	return err
}

const createProductVariation = `-- name: CreateProductVariation :one
INSERT INTO product_variations (
    product_id,
    variation_name,
    variation_value,
    regular_price,
    sale_price,
    sku,
    stock_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateProductVariationParams struct {
	ProductID      *int32         `json:"product_id"`
	VariationName  string         `json:"variation_name"`
	VariationValue string         `json:"variation_value"`
	RegularPrice   pgtype.Numeric `json:"regular_price"`
	SalePrice      pgtype.Numeric `json:"sale_price"`
	Sku            *string        `json:"sku"`
	StockID        *int32         `json:"stock_id"`
}

func (q *Queries) CreateProductVariation(ctx context.Context, arg CreateProductVariationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createProductVariation,
		arg.ProductID,
		arg.VariationName,
		arg.VariationValue,
		arg.RegularPrice,
		arg.SalePrice,
		arg.Sku,
		arg.StockID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSingleProduct = `-- name: CreateSingleProduct :one
INSERT INTO products (
    category_id,
    name,
    slug,
    description,
    type,
    regular_price,
    sale_price,
    sku,
    stock_id,
    main_image_url
)
VALUES ($1, $2, $3, $4, 'single', $5, $6, $7, $8, $9)
RETURNING id
`

type CreateSingleProductParams struct {
	CategoryID   *int32         `json:"category_id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	Description  string         `json:"description"`
	RegularPrice pgtype.Numeric `json:"regular_price"`
	SalePrice    pgtype.Numeric `json:"sale_price"`
	Sku          *string        `json:"sku"`
	StockID      *int32         `json:"stock_id"`
	MainImageUrl *string        `json:"main_image_url"`
}

func (q *Queries) CreateSingleProduct(ctx context.Context, arg CreateSingleProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSingleProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.RegularPrice,
		arg.SalePrice,
		arg.Sku,
		arg.StockID,
		arg.MainImageUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createStock = `-- name: CreateStock :one
INSERT INTO stock (
    quantity,
    low_stock_threshold
)
VALUES ($1, $2)
RETURNING id
`

type CreateStockParams struct {
	Quantity          int32  `json:"quantity"`
	LowStockThreshold *int32 `json:"low_stock_threshold"`
}

func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (int32, error) {
	row := q.db.QueryRow(ctx, createStock, arg.Quantity, arg.LowStockThreshold)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO thread (title)
VALUES ($1)
RETURNING id, title, created_at
`

func (q *Queries) CreateThread(ctx context.Context, title string) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread, title)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const createVariableProduct = `-- name: CreateVariableProduct :one
INSERT INTO products (
    category_id,
    name,
    slug,
    description,
    type,
    main_image_url
)
VALUES ($1, $2, $3, $4, 'variable', $5)
RETURNING id
`

type CreateVariableProductParams struct {
	CategoryID   *int32  `json:"category_id"`
	Name         string  `json:"name"`
	Slug         string  `json:"slug"`
	Description  string  `json:"description"`
	MainImageUrl *string `json:"main_image_url"`
}

func (q *Queries) CreateVariableProduct(ctx context.Context, arg CreateVariableProductParams) (int32, error) {
	row := q.db.QueryRow(ctx, createVariableProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.MainImageUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteMessageById = `-- name: DeleteMessageById :one
DELETE FROM message WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteMessageById(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteMessageById, id)
	err := row.Scan(&id)
	return id, err
}

const deleteMessageByThreadId = `-- name: DeleteMessageByThreadId :one
DELETE FROM message WHERE thread_id = $1
RETURNING thread_id
`

func (q *Queries) DeleteMessageByThreadId(ctx context.Context, threadID int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteMessageByThreadId, threadID)
	var thread_id int32
	err := row.Scan(&thread_id)
	return thread_id, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, content, created_at, thread_id FROM message
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.ThreadID,
	)
	return i, err
}

const getMessageByThreadPaginated = `-- name: GetMessageByThreadPaginated :many
SELECT id, content, created_at, thread_id FROM message
WHERE thread_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessageByThreadPaginatedParams struct {
	ThreadID int32 `json:"thread_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) GetMessageByThreadPaginated(ctx context.Context, arg GetMessageByThreadPaginatedParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessageByThreadPaginated, arg.ThreadID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByThread = `-- name: GetMessagesByThread :many
SELECT id, content, created_at, thread_id FROM message
WHERE thread_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMessagesByThread(ctx context.Context, threadID int32) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadById = `-- name: GetThreadById :one
SELECT id, title, created_at FROM thread WHERE id = $1
`

func (q *Queries) GetThreadById(ctx context.Context, id int32) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadById, id)
	var i Thread
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE message 
SET content = $2
WHERE id = $1
RETURNING id, content, created_at, thread_id
`

type UpdateMessageParams struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.ID, arg.Content)
	return err
}
