// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CheckPaymentStatus(ctx context.Context, transactionReference *string) (*string, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int32, error)
	CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) (int32, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	CreateProductGallery(ctx context.Context, arg CreateProductGalleryParams) error
	CreateProductVariation(ctx context.Context, arg CreateProductVariationParams) (int32, error)
	CreateSingleProduct(ctx context.Context, arg CreateSingleProductParams) (int32, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (int32, error)
	CreateVariableProduct(ctx context.Context, arg CreateVariableProductParams) (int32, error)
	GetMessageByThreadPaginated(ctx context.Context, arg GetMessageByThreadPaginatedParams) ([]Message, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
