// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	DeleteMessageByID(ctx context.Context, id string) error
	GetMessageByID(ctx context.Context, id string) (Message, error)
	GetMessagesByThread(ctx context.Context, thread string) ([]Message, error)
	UpdateMessageByID(ctx context.Context, arg UpdateMessageByIDParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
